### ISSUE TITLE
Modify README to first start whatever other program or setup steps are needed.

### ISSUE THREAD

**Issue by szalapski** [PeterTheobald/KeyboardFrequencies#5]
I assume that, to run `download`,  I need to first run something else.  What do I need to run on Windows?

Instead of `download`, I ran `git clone https://github.com/PeterTheobald/KeyboardFrequencies.git` then `cd .\KeyboardFrequencies\`, then your other two steps, and it worked.

Maybe also need to cue us to run `winget install python` on Windows?

**Comment by PeterTheobald** [comment]
Every Windows since the May 2019 update has had a Python program already installed that takes you directly to the Python installation page on the Windows Store. Is your Windows older than 2019?
I'll add a note to the Readme for people with older Windows.

**Comment by PeterTheobald** [comment]
instructions added to Readme
